# Generated by Django 4.0.6 on 2022-07-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
    ]
