# Generated by Django 4.0.6 on 2022-07-28 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_profile_level_profile_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hostel',
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hostel')),
            ],
        ),
    ]
