# Generated by Django 4.0.6 on 2022-07-28 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_profile_hostel_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.room'),
        ),
    ]
